repository: git@gitlab.quartsoft.com:mage2-extensions/mageb2bportal.git
branch: stage-stable
http_user: www-data
deploy_path: /mnt/d/Work/0__Projects/Deployer/Shell/app
languages: [ru_RU, en_US, pl_PL]
base_url: http://loc.dep/
backend_url: admin
deploy_mode: developer
default_admin: 
  name: admin
  password: magento1
  email: admin@example.com
db:
  host: 127.0.0.1
  dbname: b2b_new
  username: root
  password: root
